#!/usr/bin/env python3
"""Regenerate every iOS alternate app icon, and the Dart copy of the same art.

Run after any change to tool/icons/app_icon_art.json:

    python3 tool/icons/make_alternate_icons.py

Needs Pillow (`pip3 install Pillow`), nothing else: no numpy on this Mac.

The Home Screen icon is a plant shape in a colour (see
lib/features/app_icon/app_icon_catalog.dart): four shapes that grow with
someone's full days, times twenty-five colours: the Night family Aziz picked
on 2026-09-25, then black with a white plant and seven light colours with a
dark one (white, vanilla, matcha, lavender on 2026-09-26; beige, mist blue,
mint on 2026-09-27), then Doum's, a cream plant on the mascot's green
(2026-09-28, free with its theme). All 100 are written as single-size 1024
sets under ios/Runner/Assets.xcassets/AlternateIcons/, one folder per icon,
named AppIcon-<shape>-<colour>. The seasonal icons (Ramadan) come after
them, one set each, named AppIcon-<id>: a shape in colours of their own
with one mark on top (the crescent). The Runner target's
ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS makes actool size them and
list them in the built Info.plist, so there is no name list to keep in step.

The same file also writes lib/features/app_icon/app_icon_art.g.dart, which
the app draws its previews from, and assets/images/icon_app.png, the shipped
icon (the one primary_icon.py names: Doum's sprout since 2026-09-30), which
the rest of the icon scripts build iOS's AppIcon, Android's launcher icon and
the Play listing from. One source for all of them is the point: a picker tile
can never show a plant the phone would not get, and the shipped icon is the
same pixels as its own tile. Its alternate set is still written: a phone that
picked it while it was an alternate keeps a name that exists (it reads back
as the shipped icon, see AppIconChoice.fromIosName).

Every path is M/L/Z only, traced from the original gold-on-emerald
assets/images/icon_app.png at 99.5% overlap. Polygons are filled at 4x and
box-filtered down, which is exactly one-pixel anti-aliasing. Output is RGB
with no alpha, like AppIcon.
"""
import json
import pathlib
import re
import shutil

from PIL import Image, ImageDraw

import primary_icon

ROOT = pathlib.Path(__file__).resolve().parents[2]
ART = ROOT / "tool/icons/app_icon_art.json"
DST = ROOT / "ios/Runner/Assets.xcassets/AlternateIcons"
DART = ROOT / "lib/features/app_icon/app_icon_art.g.dart"
SHIPPED = ROOT / "assets/images/icon_app.png"

SIZE = 1024
SUPER = 4
PRIMARY = (primary_icon.SHAPE, primary_icon.COLOUR)

CONTENTS = {
    "images": [
        {"filename": "icon.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"}
    ],
    "info": {"author": "xcode", "version": 1},
}
FOLDER = {"info": {"author": "xcode", "version": 1}}


def rgb(hexc):
    h = hexc.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def lift(hexc, t):
    """The flower: the sprout colour moved toward white. Same sum as AppIconArt.

    Rounded half up, as Dart's round() does for these positive numbers;
    Python's round() goes half to even and would drift by one here and there.
    """
    return tuple(int(c + (255 - c) * t + 0.5) for c in rgb(hexc))


def polygons(d):
    """M/L/Z path data to a list of point lists."""
    out = []
    for sub in re.findall(r"M[^Z]*Z", d):
        nums = [float(n) for n in re.findall(r"-?\d+(?:\.\d+)?", sub)]
        out.append(list(zip(nums[0::2], nums[1::2])))
    return out


def render(shape, colour, flower_lift, mark=None):
    """One icon. [mark] is a seasonal icon's own (path, colour), drawn last.

    A colour's own "flowerLift" wins over [flower_lift]: the light colours
    set 0, so the bloom's flower is the plant's own dark ink with the ground
    showing through its eye. Lifted toward white it would go grey on them.
    """
    n = SIZE * SUPER
    k = n / 1024
    img = Image.new("RGB", (n, n), rgb(colour["ground"]))
    layers = [(shape["sprout"], rgb(colour["sprout"]))]
    if "flower" in shape:
        t = colour.get("flowerLift", flower_lift)
        layers.append(([shape["flower"]], lift(colour["sprout"], t)))
        layers.append(([shape["eye"]], rgb(colour["ground"])))
    if mark is not None:
        layers.append(([mark[0]], rgb(mark[1])))
    for paths, fill in layers:
        mask = Image.new("L", (n, n), 0)
        draw = ImageDraw.Draw(mask)
        for d in paths:
            for poly in polygons(d):
                draw.polygon([(x * k, y * k) for x, y in poly], fill=255)
        img.paste(Image.new("RGB", (n, n), fill), mask=mask)
    return img.resize((SIZE, SIZE), Image.BOX)


def dart_string(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$") + "'"


def write_dart(art):
    lines = [
        "// GENERATED by tool/icons/make_alternate_icons.py from",
        "// tool/icons/app_icon_art.json. Do not edit by hand: change the JSON and",
        "// rerun the script, which rewrites this file and the iOS icon sets together.",
        "",
        "part of 'app_icon_art.dart';",
        "",
        "/// Each shape's paths on the 1024 grid: sprout-coloured parts, then the",
        "/// bloom's petals and the eye at their centre (ground-coloured).",
        "const Map<String, ({List<String> sprout, String? flower, String? eye})> _kShapeArt = {",
    ]
    for sid, shape in art["shapes"].items():
        parts = ", ".join(dart_string(p) for p in shape["sprout"])
        flower = dart_string(shape["flower"]) if "flower" in shape else "null"
        eye = dart_string(shape["eye"]) if "eye" in shape else "null"
        lines.append(f"  '{sid}': (sprout: [{parts}], flower: {flower}, eye: {eye}),")
    lines += [
        "};",
        "",
        "/// Ground and sprout for every colour, as 0xAARRGGBB, and how far the",
        "/// bloom's flower is lifted from the sprout toward white.",
        "const Map<String, ({int ground, int sprout, double flowerLift})> _kColourArt = {",
    ]
    for c in art["colours"]:
        g = "0xFF" + c["ground"].lstrip("#").upper()
        s = "0xFF" + c["sprout"].lstrip("#").upper()
        f = c.get("flowerLift", art["flowerLift"])
        lines.append(f"  '{c['id']}': (ground: {g}, sprout: {s}, flowerLift: {float(f)}),")
    lines += [
        "};",
        "",
        "/// The seasonal icons: one shape in colours of their own, with a mark",
        "/// drawn over it (Ramadan's crescent).",
        "const Map<String, ({String shape, int ground, int sprout, String mark, int markColour})> _kSeasonalArt = {",
    ]
    for sid, season in art.get("seasonal", {}).items():
        g = "0xFF" + season["ground"].lstrip("#").upper()
        s = "0xFF" + season["sprout"].lstrip("#").upper()
        m = "0xFF" + season["markColour"].lstrip("#").upper()
        lines.append(
            f"  '{sid}': (shape: '{season['shape']}', ground: {g}, sprout: {s}, "
            f"mark: {dart_string(season['mark'])}, markColour: {m}),"
        )
    lines += ["};", "", f"const double _kFlowerLift = {art['flowerLift']};", ""]
    DART.write_text("\n".join(lines))


def main() -> None:
    art = json.loads(ART.read_text())
    if DST.exists():
        shutil.rmtree(DST)
    DST.mkdir(parents=True)
    (DST / "Contents.json").write_text(json.dumps(FOLDER, indent=2) + "\n")
    written = 0
    shipped = None
    for sid, shape in art["shapes"].items():
        for colour in art["colours"]:
            folder = DST / f"AppIcon-{sid}-{colour['id']}.appiconset"
            folder.mkdir()
            icon = render(shape, colour, art["flowerLift"])
            icon.save(folder / "icon.png", optimize=True)
            (folder / "Contents.json").write_text(json.dumps(CONTENTS, indent=2) + "\n")
            written += 1
            if (sid, colour["id"]) == PRIMARY:
                shipped = icon
    for sid, season in art.get("seasonal", {}).items():
        folder = DST / f"AppIcon-{sid}.appiconset"
        folder.mkdir()
        icon = render(
            art["shapes"][season["shape"]],
            season,
            art["flowerLift"],
            mark=(season["mark"], season["markColour"]),
        )
        icon.save(folder / "icon.png", optimize=True)
        (folder / "Contents.json").write_text(json.dumps(CONTENTS, indent=2) + "\n")
        written += 1
    write_dart(art)
    if shipped is None:
        raise SystemExit(f"primary icon {PRIMARY} is not in {ART.relative_to(ROOT)}")
    shipped.save(SHIPPED, optimize=True)
    print(f"{written} alternate icons in {DST.relative_to(ROOT)}; wrote {DART.relative_to(ROOT)}")
    print(f"shipped icon {PRIMARY[0]}-{PRIMARY[1]} -> {SHIPPED.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
